### ISSUE TITLE
supervisord突然无法正常使用

### ISSUE THREAD

**Issue by thank243** [orvice/ss-panel#190]
DEFAULT_USER = getpass.getuser()
  File "/usr/lib/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 65534'
Traceback (most recent call last):
  File "/usr/share/shadowsocks/server.py", line 5, in <module>
    import db_transfer
  File "/usr/share/shadowsocks/db_transfer.py", line 5, in <module>
    import cymysql
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 42, in <module>
    from cymysql.connections import Connection
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 20, in <module>
    DEFAULT_USER = getpass.getuser()
  File "/usr/lib/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 65534'

很奇怪，手动运行 python /usr/share/shadowsocks/server.py -c  /usr/share/shadowsocks/config.json
一切正常。写入supervisor后就一直提示以上错误，确认数据库账号密码都正确，因为手动运行正常。

**Comment by akw28888** [comment]
這不是ss-panel的問題000000000.
