### ISSUE TITLE
Uncaught Error: Class 'PDO' not found in /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php:49

### ISSUE THREAD

**Issue by relei1988** [orvice/ss-panel#495]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 7.0.6
* ss-panel version/ ss-panel版本:V3
* 其他环境信息(Nginx,系统等):nginx 1.10.0       centos 6 x64

### Description of the problem / 问题描述
在这里输入描述信息.
执行php xcat createAdmin  添加管理员时报错,
```
PHP Fatal error:  Uncaught Error: Class 'PDO' not found in /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php:49
Stack trace:
#0 /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php(37): Illuminate\Database\Capsule\Manager->setupDefaultConfiguration()
#1 /home/wwwroot/ss-panel/app/Services/Boot.php(40): Illuminate\Database\Capsule\Manager->__construct()
#2 /home/wwwroot/ss-panel/bootstrap/app.php(25): App\Services\Boot::bootDb()
#3 /home/wwwroot/ss-panel/xcat(3): require('/home/wwwroot/s...')
#4 {main}
  thrown in /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php on line 49
[root@centos-512mb-sfo1-01 ss-panel]# php xcat resetTraffic
PHP Fatal error:  Uncaught Error: Class 'PDO' not found in /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php:49
Stack trace:
#0 /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php(37): Illuminate\Database\Capsule\Manager->setupDefaultConfiguration()
#1 /home/wwwroot/ss-panel/app/Services/Boot.php(40): Illuminate\Database\Capsule\Manager->__construct()
#2 /home/wwwroot/ss-panel/bootstrap/app.php(25): App\Services\Boot::bootDb()
#3 /home/wwwroot/ss-panel/xcat(3): require('/home/wwwroot/s...')
#4 {main}
  thrown in /home/wwwroot/ss-panel/vendor/illuminate/database/Capsule/Manager.php on line 49
```
尝试在php.ini中添加extension="pod.so"等,但无果,求解

**Comment by voti** [comment]
```
#if you are ubuntu server
sudo apt-get install php7.0-mysql
```

**Comment by relei1988** [comment]
ok i'll try,feedback later,thanks

**Comment by relei1988** [comment]
it's done thanks
