### ISSUE TITLE
SSPANEL-V3多节点连接前端问题

### ISSUE THREAD

**Issue by jack338c** [orvice/ss-panel#547]
前后端在一个VPS上时工作正常
不在一个VPS上时，出现下面错误，请好朋友帮指点下，小弟感激不尽！

注：在数据库上把Host已改为任意主机“%”，数据库名密码的都对应的，还有，后端MYSQL_HOST改成了前段VPSIP了

root@64:~# python /root/shadowsocks/server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-07-09 07:35:49 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.                                 0
Shadowsocks
2016-07-09 07:35:49 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('74.                                 82.42.42', 53), ('4.2.2.1', 53), ('8.8.4.4', 53)]
2016-07-09 07:36:52 ERROR    db_transfer.py:218 Traceback (most recent call last                                 ):
  File "/root/shadowsocks/db_transfer.py", line 213, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 90, in pull_db_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in                                  Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244                                 , in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409                                 , in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (s                                 elf.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '159.203.*****(110                                 )")

**Comment by orvice** [comment]
Can't connect to MySQL server 

连不上mysql

**Comment by jack338c** [comment]
@orvice 
试了另外一个远程VPS 连这个前端，也是这样的错误

root@ubuntu:~# python /root/shadowsocks/server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-07-09 08:44:27 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.                   0
Shadowsocks
2016-07-09 08:44:27 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53)]
2016-07-09 08:46:34 ERROR    db_transfer.py:218 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 213, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 90, in pull_db_all_user
    passwd=get_config().MYSQL_PASS, db=get_config().MYSQL_DB, charset='utf8')
  File "/usr/local/lib/python2.7/dist-packages/cymysql/__init__.py", line 85, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 244, in __init__
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 409, in _connect
    raise OperationalError(2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e.args[0]))
OperationalError: (2003, "Can't connect to MySQL server on '159.203.25*** (110)")


注：3个VPS防火墙都没装或没启用

这有可能是哪些什么原因啊?

**Comment by jack338c** [comment]
前后端在同一VPS上是正常的

root@ubuntu-512mb-sfo1-01:~# python /root/shadowsocks/server.py
loaded collections.OrderedDict
IPv6 support
INFO: loading config from user-config.json
2016-07-09 21:06:55 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.                      0
Shadowsocks
2016-07-09 21:06:55 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8                      .4.4', 53)]
2016-07-09 21:06:55 INFO     db_transfer.py:172 db start server at port [1025] p                      ass [UtU245]
2016-07-09 21:06:55 INFO     server_pool.py:128 starting server at [::]:1025
2016-07-09 21:06:55 INFO     server_pool.py:154 starting server at 0.0.0.0:1025
