### ISSUE TITLE
php xcat sendDiaryMail 出错了

### ISSUE THREAD

**Issue by jack338c** [orvice/ss-panel#550]
/home/wwwroot/default/ss-panel# php xcat sendDiaryMail                                                                                        Send daily mail to user: 1PHP Fatal error:  Uncaught exception 'Mailgun\Connecti                                                                                        on\Exceptions\MissingEndpoint' with message 'The endpoint you've tried to access                                                                                         does not exist. Check your URL.' in /home/wwwroot/default/ss-panel/vendor/mailg                                                                                        un/mailgun-php/src/Mailgun/Connection/RestClient.php:133
Stack trace:
#0 /home/wwwroot/default/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connect                                                                                        ion/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Gu                                                                                        zzle\Http\Message\Response))
#1 /home/wwwroot/default/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun                                                                                        .php(80): Mailgun\Connection\RestClient->post('/messages', Array, Array)
#2 /home/wwwroot/default/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun                                                                                        .php(36): Mailgun\Mailgun->post('/messages', Array, Array)
#3 /home/wwwroot/default/ss-panel/app/Services/Mail/Mailgun.php(50): Mailgun\Mai                                                                                        lgun->sendMessage('', Array, Array)
#4 /home/wwwroot/default/ss-panel/app/Services/Mail.php(71): App\Services\Mail\M                                                                                        ailgun->send('jack338c@gmail....', 'ssg-\xE6\xAF\x8F\xE6\x97\xA5\xE6\xB5\x81\xE9                                                                                        \ in /home/wwwroot/default/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Conne                                                                                        ction/RestClient.php on line 133

请问，这属于什么情况
谢谢你！

**Comment by ornodus** [comment]
mailgun账号是否验证了？
参考
https://github.com/mailgun/mailgun-php/issues/71

**Comment by xxsxx** [comment]
mailgun_sender 这个应该填那个。。。
