### ISSUE TITLE
Mailgun的问题麻烦看下

### ISSUE THREAD

**Issue by gy15617** [orvice/ss-panel#567]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 
* ss-panel version/ ss-panel版本:
* 其他环境信息(Nginx,系统等):

### Description of the problem / 问题描述
在这里输入描述信息.

运行环境 :php 5.6.22
ss-panel:v3(7月24日git)
nginx :1.10.0
CentOS 7 x64 kernel：4.5.5-x86_64-linode69

MailGun在.env的配置怎么配置？API key那个按照官方的Key-xxxxxxx...填进去，mailgun_sender和mailgun_domain分别指的什么？我把我的域名按照官方的引导设置了TXT CNNAME MX记录等，domain填的域名（好比 baidu.com），sender填的例如 postmaster@baidu.com 
然后发送流量信息提示如下错误，也可能是我不会配置配置错了导致的，所以问下这两个项怎么配置？对应官方给的什么？感谢您的帮助！
错误如下 
Send daily mail to user: 1PHP Fatal error:  Uncaught exception 'Mailgun\Connection\Exceptions\MissingRequiredParameters' with message 'The parameters passed to the API were invalid. Check your inputs!' in /home/wwwroot/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php:127
Stack trace:
#0 /home/wwwroot/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php(90): Mailgun\Connection\RestClient->responseHandler(Object(Guzzle\Http\Message\Response))
#1 /home/wwwroot/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(80): Mailgun\Connection\RestClient->post('sandbox00a5814e...', Array, Array)
#2 /home/wwwroot/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php(36): Mailgun\Mailgun->post('sandbox00a5814e...', Array, Array)
#3 /home/wwwroot/ss-panel/app/Services/Mail/Mailgun.php(50): Mailgun\Mailgun->sendMessage('sandbox00a5814e...', Array, Array)
#4 /home/wwwroot/ss-panel/app/Services/Mail.php(71): App\Services\Mail\Mailgun->send('me@iextreme.cc', 'IceSock-\xE6\xAF\x8F\xE6\x97\xA5\xE6...', '<!DOCTYPE  in /home/wwwroot/ss-panel/vendor/mailgun/mailgun-php/src/Mailgun/Connection/RestClient.php on line 127

**Comment by liyangio** [comment]
看看你的DB里是不是少了一个sp_email_verify的表

**Comment by zuoruizhi** [comment]
The parameters passed to the API were invalid. Mailgun没有被禁？或者mailgun配置

**Comment by thank243** [comment]
好像是mailgun的问题，需要添加自己的域名，sandbox只会发送给认证用户。
