### ISSUE TITLE
did it support ssr?

### ISSUE THREAD

**Issue by iefnuy** [orvice/ss-panel#619]
* PHP Version /PHP版本: 5.6.23
* ss-panel version/ ss-panel版本:3.4.2
* 其他环境信息(Nginx,系统等):nginx

支持ssr的混淆协议吗？

**Comment by iefnuy** [comment]
当用户登录选择记住我，退出时主页出现
warning: file_get_contents(/home/wwwroot/mirror.hk/bootstrap/..//storage//framework/sessions/fd22db319d4b43b5a5d7e3188c2567b972d5d9a27773676f7f18915c30d3c27b): failed to open stream: No such file or directory in /home/wwwroot/abc.com/app/Services/Cache/File.php on line 43

登录页出现
Warning: file_get_contents(/home/wwwroot/*****/bootstrap/..//storage//framework/sessions/fd22db319d4b43b5a5d7e3188c2567b972d5d9a27773676f7f18915c30d3c27b): failed to open stream: No such file or directory in /home/wwwroot/*******/app/Services/Cache/File.php on line 43

Fatal error: Uncaught exception 'RuntimeException' with message 'Unexpected data in output buffer. Maybe you have characters before an opening <?php tag?' in /home/wwwroot/*****/vendor/slim/slim/Slim/App.php:552 Stack trace: #0 /home/wwwroot/*****/vendor/slim/slim/Slim/App.php(344): Slim\App->finalize(Object(Slim\Http\Response)) #1 /home/wwwroot/********/vendor/slim/slim/Slim/App.php(298): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #2 /home/wwwroot/****/public/index.php(13): Slim\App->run() #3 {main} thrown in /home/wwwroot/*****/vendor/slim/slim/Slim/App.php on line 552

要清楚cooike才好，怎么解决？？

**Comment by Asheblog** [comment]
理论上需要破瓦酱的sspanel ssr专版

**Comment by zcdll** [comment]
我遇到这个问题很久了，看了你的提示把 debug 打开后，确实就不报错了，谢谢！ @iefnuy

**Comment by Antairez** [comment]
@Asheblog 有该项目的地址吗？
