### ISSUE TITLE
config对象没有实例化？

### ISSUE THREAD

**Issue by lbp0200** [orvice/ss-panel#675]
config对象没有实例化？

## 运行环境

* PHP Version /PHP版本: php 7
* ss-panel version/ ss-panel版本:v3.4.5
* 其他环境信息(Nginx,系统等):bash

### Description of the problem / 问题描述
```bash
php xcat 
PHP Fatal error:  Uncaught Error: Using $this when not in object context in /opt/www/ss-panel/vendor/illuminate/config/Repository.php:49
Stack trace:
#0 /opt/www/ss-panel/app/Services/Boot.php(20): Illuminate\Config\Repository::get('debug')
#1 /opt/www/ss-panel/bootstrap/app.php(20): App\Services\Boot::setDebug()
#2 /opt/www/ss-panel/xcat(3): require('/opt/www/ss-pan...')
#3 {main}
  thrown in /opt/www/ss-panel/vendor/illuminate/config/Repository.php on line 49
```

**Comment by orvice** [comment]
是用 `composer install` 安装依赖的吗

**Comment by lbp0200** [comment]
ubuntu16.04，`composer update`安装

**Comment by orvice** [comment]
@lbp0200 请用 composer install  安装依赖，update会更新到最新依赖。
