### ISSUE TITLE
使用远程数据库时执行php xcat createAdmin尝试连接本地数据库导致失败

### ISSUE THREAD

**Issue by lydasia** [orvice/ss-panel#686]
## 运行环境

* PHP Version /PHP版本: 7.1
* ss-panel version/ ss-panel版本:v3.4.5
* 其他环境信息(Nginx,系统等):Apache2, Debian 8

### Description of the problem / 问题描述

在.env中指定了使用远程数据库，执行php xcat createAdmin创建管理员账户时发生错误，查看输出发现尝试了连接本地数据库服务器，而不是指定的远程数据库。

输出如下：
start create admin accountPHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'root'@'【这里显示的是本机IP而不是远程数据库IP】' (using password: YES) in /var/www/***/vendor/illuminate/database/Connectors/Connector.php:55
Stack trace:
#0 /var/www/***/vendor/illuminate/database/Connectors/Connector.php(55): PDO->__construct('mysql:host=***....', 'root', '*******', Array)
#1 /var/www/***/vendor/illuminate/database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=***....', Array, Array)
#2 /var/www/***/vendor/illuminate/database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /var/www/***/vendor/illuminate/database/Connection.php(875): call_user_func(Object(Closure))
#5 /var/www/***/vendor/illuminate/database/Connection.php(743): Illuminate\Database\Connection->getPdo in /var/www/***/vendor/illuminate/database/Connectors/Connector.php on line 55

**Comment by luyuxuan** [comment]
自己手动添加个账号吧
字段啥意思不懂问我
弄个phpmyadmin

**Comment by davidsongcn** [comment]
在目录下 vi .env 文件
找到数据库配置
看数据库名、用户名、密码是否正确

**Comment by gtihubAlimjan** [comment]
应该是权限问题。不说说实话。ss-panel数据库设计很多小问题。比如有些字段的timestamp必须给timestamp不然写入不进去数据。有些还有默认值的情况下也不能直接写入数据，必须给默认值。。其他v4全版本（目前v4没有很多功能）
