### ISSUE TITLE
安装步骤到添加管理员报错。求助！

### ISSUE THREAD

**Issue by SBgfw** [orvice/ss-panel#700]
** 开issue前请确认: **
* 安装问题等错误请开启debug模式,并附上debug log
* 安全问题请发邮箱 sspanel#orx.me
* 未填写运行环境的issue将会被直接关闭
* 一个issue请只题一个问题,多个问题分多个issue开.

## 运行环境

* PHP Version /PHP版本: 7.1
* ss-panel version/ ss-panel版本:3.4.5
* 其他环境信息(Nginx,系统等):Nginx（lnmp）

### Description of the problem / 问题描述
在这里输入描述信息.
按照官方文档安装，[https://sspanel.xyz/docs/intro/installation](url)
之后配置了.env，数据库版本为(db10.1)，用户名密码等均无错，
访问域名可以显示主页，但是进入后台、注册、等页面报错404.
然后发现ss-panel目录下有个install.sh,怀疑是没有运行这个导致public目录下的文件没有安装完整。
结果# sh install.sh ，然后报错如下信息：
Press [Y] to create admin.....                                                                                                                                                              按下[Y]确认来确认创建管理员账户..... y
start create admin accountPHP Fatal error:  Uncaught InvalidArgumentException: U                                                                                                                                                             nsupported driver [root] in /data/3w/ss3/ss-panel/vendor/illuminate/database/Con                                                                                                                                                             nectors/ConnectionFactory.php:232
Stack trace:
#0 /data/3w/ss3/ss-panel/vendor/illuminate/database/Connectors/ConnectionFactory                                                                                                                                                             .php(64): Illuminate\Database\Connectors\ConnectionFactory->createConnection('ro                                                                                                                                                             ot', Object(Closure), 'ssp', '', Array)
#1 /data/3w/ss3/ss-panel/vendor/illuminate/database/Connectors/ConnectionFactory                                                                                                                                                             .php(49): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnecti                                                                                                                                                             on(Array)
#2 /data/3w/ss3/ss-panel/vendor/illuminate/database/DatabaseManager.php(176): Il                                                                                                                                                             luminate\Database\Connectors\ConnectionFactory->make(Array, 'default')
#3 /data/3w/ss3/ss-panel/vendor/illuminate/database/DatabaseManager.php(68): Ill                                                                                                                                                             uminate\Database\DatabaseManager->makeConnection('default')
#4 /data/3w/ss3/ss-panel/vendor/illuminate/database/Eloquent/Model.php(3280): Il                                                                                                                                                             luminate\Database\DatabaseManager->connection('default')
#5 /data/3w/ss3/ss-panel/vendor/illuminate/database/Eloquent/Mo in /data/3w/ss3/                                                                                                                                                             ss-panel/vendor/illuminate/database/Connectors/ConnectionFactory.php on line 232

请大神帮忙看下，是什么原因导致呢？

**Comment by SBgfw** [comment]
@orvice

**Comment by orvice** [comment]
数据库信息有问题
